"""StyleGuide dataclass — the output of document profiling.

A StyleGuide is a structured description of a document's writing style,
generated by the doc_profiler module. It is used downstream to inject
style hints into the translation prompt via build_translate_prompt().
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class StyleGuide:
    """Structured description of a document's writing style.

    Fields:
        tone: Overall tone — "formal" | "informal" | "academic" | "casual" | etc.
        register: Language register — "technical" | "conversational" | "literary" | etc.
        target_audience: Intended readers — "developers" | "general public" | etc.
        key_conventions: Bullet list of style rules the document follows.
        vocabulary: Domain-specific terms to prefer.
        avoid: Words or phrases to avoid.
        summary: 1-2 sentence description of the document's style.
    """

    tone: str = ""
    register: str = ""
    target_audience: str = ""
    key_conventions: list[str] = field(default_factory=list)
    vocabulary: list[str] = field(default_factory=list)
    avoid: list[str] = field(default_factory=list)
    summary: str = ""

    def to_dict(self) -> dict:
        return {
            "tone": self.tone,
            "register": self.register,
            "target_audience": self.target_audience,
            "key_conventions": list(self.key_conventions),
            "vocabulary": list(self.vocabulary),
            "avoid": list(self.avoid),
            "summary": self.summary,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "StyleGuide":
        """Build a StyleGuide from a dict. Ignores unknown keys for forward compat."""
        return cls(
            tone=data.get("tone", ""),
            register=data.get("register", ""),
            target_audience=data.get("target_audience", ""),
            key_conventions=list(data.get("key_conventions", []) or []),
            vocabulary=list(data.get("vocabulary", []) or []),
            avoid=list(data.get("avoid", []) or []),
            summary=data.get("summary", ""),
        )

    def to_prompt_section(self) -> str:
        """Format this StyleGuide as a section to inject into a translation prompt.

        Returns a multi-line string starting with "[Style Guide]". If all
        fields are empty, returns an empty string (no section).
        """
        if not any([self.tone, self.register, self.target_audience,
                    self.key_conventions, self.vocabulary, self.avoid,
                    self.summary]):
            return ""
        lines = ["[Style Guide]"]
        if self.tone:
            lines.append(f"Tone: {self.tone}")
        if self.register:
            lines.append(f"Register: {self.register}")
        if self.target_audience:
            lines.append(f"Target audience: {self.target_audience}")
        if self.summary:
            lines.append(f"Summary: {self.summary}")
        if self.key_conventions:
            lines.append("Key conventions:")
            for c in self.key_conventions:
                lines.append(f"  - {c}")
        if self.vocabulary:
            lines.append("Preferred vocabulary:")
            for v in self.vocabulary:
                lines.append(f"  - {v}")
        if self.avoid:
            lines.append("Avoid:")
            for a in self.avoid:
                lines.append(f"  - {a}")
        return "\n".join(lines)

    def to_json_file(self, path: Path | str) -> None:
        """Serialize to a JSON file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(self.to_dict(), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

    @classmethod
    def from_json_file(cls, path: Path | str) -> "StyleGuide":
        """Load from a JSON file."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"StyleGuide file not found: {path}")
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls.from_dict(data)
