"""OL CLI smoke: invoke `translate-md` and `translate-xliff` end-to-end.

Spawns the OL CLI as a real subprocess (not in-process CliRunner) so we
exercise the same code path users hit from the shell. The LLM call is
intercepted via OMNI_TEST_FAKE_LLM=1, which OL's own _translate_md_async /
_translate_xliff_async short-circuit handlers honour.

Inputs are generated by running the OPP CLI first (using a real DOCX
fixture) so we test the actual user workflow:

    OPP --target-format=both <docx> -o <intermediate_dir>/
        -> intermediate_dir/<docx>.md
        -> intermediate_dir/<docx>.xlf
        -> intermediate_dir/<docx>_manifest.json
        -> intermediate_dir/<docx>.skeleton.zip

    ol translate-md  <intermediate_dir>/<docx>.md   -o <out>/
    ol translate-xliff <intermediate_dir>/<docx>.xlf -o <out>/

Run with:
    cd /mnt/d/贯维/Omni_Suite/Omni_Localizer
    OMNI_TEST_FAKE_LLM=1 pytest tests/test_cli_smoke.py -v --tb=short
"""
from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest


VENV_PY = "/mnt/d/贯维/Omni_Suite/.venv_ol/bin/python"
OL_DIR = Path("/mnt/d/贯维/Omni_Suite/Omni_Localizer")
OPP_DIR = Path("/mnt/d/贯维/Omni_Suite/Omni_Pre_Processor")
REPO_ROOT = Path("/mnt/d/贯维/Omni_Suite")

HAIER_DOCX = REPO_ROOT / "爱上海尔_第二章_全球创牌 - E2E测试专用.docx"
MERIDIAN_DOCX = REPO_ROOT / "Meridian_Robotics_Product_Overview_E2E.docx"

_BASE_ENV = {
    **os.environ,
    "OMNI_TEST_FAKE_LLM": "1",
    "PYTHONUNBUFFERED": "1",
    "PYTHONIOENCODING": "utf-8",
}


def run_ol(*args: str, timeout: int = 240) -> subprocess.CompletedProcess:
    """Invoke `python -m ol_cli ...` in OL_DIR with the venv interpreter."""
    cmd = [VENV_PY, "-m", "ol_cli", *args]
    return subprocess.run(
        cmd,
        cwd=str(OL_DIR),
        capture_output=True,
        text=True,
        timeout=timeout,
        env=_BASE_ENV,
    )


def run_opp_extract(docx: Path, out_dir: Path, target_format: str = "both") -> None:
    """Run OPP CLI to produce MD/XLIFF intermediates for `docx` in `out_dir`."""
    cmd = [
        VENV_PY, "-m", "opp.cli",
        str(docx),
        "--target-format", target_format,
        "--source-lang", "en", "--target-lang", "zh",
        "--output-dir", str(out_dir),
    ]
    proc = subprocess.run(
        cmd,
        cwd=str(OPP_DIR),
        capture_output=True,
        text=True,
        timeout=240,
        env=_BASE_ENV,
    )
    assert proc.returncode == 0, (
        f"OPP pre-extract failed: exit={proc.returncode}\n"
        f"stderr(last 1500)={proc.stderr[-1500:]}"
    )


@pytest.fixture(scope="module", autouse=True)
def _check_real_fixtures():
    for p in (HAIER_DOCX, MERIDIAN_DOCX):
        if not p.exists():
            pytest.skip(f"Real fixture missing: {p}")


@pytest.fixture(scope="module")
def opp_intermediates(tmp_path_factory) -> dict[str, Path]:
    """Run OPP once on a real DOCX; reuse the MD/XLIFF for every test."""
    out = tmp_path_factory.mktemp("ol_opp_intermediates")
    run_opp_extract(MERIDIAN_DOCX, out, target_format="both")
    stem = MERIDIAN_DOCX.stem
    md = out / f"{stem}.md"
    xlf = out / f"{stem}.xlf"
    assert md.exists() and md.stat().st_size > 0, f"no MD at {md}"
    assert xlf.exists() and xlf.stat().st_size > 0, f"no XLF at {xlf}"
    return {"md": md, "xlf": xlf, "dir": out, "stem": stem}


# --- Tests ------------------------------------------------------------------


class TestCLIBasics:
    def test_help(self):
        proc = run_ol("--help")
        assert proc.returncode == 0, f"stderr: {proc.stderr[:1000]}"
        assert "translate-md" in proc.stdout
        assert "translate-xliff" in proc.stdout
        assert "translate-batch" in proc.stdout
        assert "extract-warnings" in proc.stdout

    def test_version(self):
        proc = run_ol("--version")
        assert proc.returncode == 0, f"stderr: {proc.stderr[:1000]}"
        assert "version" in proc.stdout.lower() or "ol" in proc.stdout.lower()

    def test_translate_md_help(self):
        proc = run_ol("translate-md", "--help")
        assert proc.returncode == 0
        assert "--output-dir" in proc.stdout
        assert "--source-lang" in proc.stdout
        assert "--target-lang" in proc.stdout

    def test_translate_xliff_help(self):
        proc = run_ol("translate-xliff", "--help")
        assert proc.returncode == 0
        assert "--output-dir" in proc.stdout


class TestTranslateMD:
    """`ol translate-md <input.md> -o <out>/` end-to-end."""

    def test_translate_md_produces_output(self, opp_intermediates, tmp_path):
        out = tmp_path / "md_out"
        proc = run_ol(
            "translate-md", str(opp_intermediates["md"]),
            "-o", str(out),
            "-s", "en", "-t", "zh",
        )
        assert proc.returncode == 0, (
            f"exit={proc.returncode}\n"
            f"stdout(last 1000)={proc.stdout[-1000:]}\n"
            f"stderr(last 1500)={proc.stderr[-1500:]}"
        )
        # The translated file is written under <out>/<basename>.md
        out_files = list(out.glob("*.md"))
        assert out_files, f"no .md produced in {out} (found: {list(out.iterdir())})"
        translated = out_files[0]
        content = translated.read_text(encoding="utf-8")
        # OL adds a YAML frontmatter with OL provenance.
        assert content.startswith("---"), f"no frontmatter in:\n{content[:200]}"
        assert "processor:" in content
        assert '"OL"' in content
        # Body should be non-empty.
        body = content.split("---", 2)[-1].strip()
        assert len(body) > 0, "translated body is empty"

    def test_translate_md_explicit_output_dir(self, opp_intermediates, tmp_path):
        """Document the -o / --output-dir override path with an explicit value.

        Note: OL's translate-md option is declared as
        `typer.Option("--output-dir", "-o", ...)`, which makes the literal
        string "--output-dir" the *default* value. Without -o, OL still runs
        and writes to a literal directory called "--output-dir/" — that
        surprising behavior is captured here by always passing an explicit
        -o, so we test the intended workflow.
        """
        out = tmp_path / "explicit_out"
        proc = run_ol(
            "translate-md", str(opp_intermediates["md"]),
            "-o", str(out),
            "-s", "en", "-t", "zh",
        )
        assert proc.returncode == 0, f"stderr: {proc.stderr[-1000:]}"
        assert out.exists()
        assert any(out.glob("*.md"))


class TestTranslateXLIFF:
    """`ol translate-xliff <input.xlf> -o <out>/` end-to-end."""

    def test_translate_xliff_produces_output(self, opp_intermediates, tmp_path):
        out = tmp_path / "xlf_out"
        proc = run_ol(
            "translate-xliff", str(opp_intermediates["xlf"]),
            "-o", str(out),
            "-s", "en", "-t", "zh",
        )
        assert proc.returncode == 0, (
            f"exit={proc.returncode}\n"
            f"stdout(last 1000)={proc.stdout[-1000:]}\n"
            f"stderr(last 1500)={proc.stderr[-1500:]}"
        )
        out_files = list(out.glob("*.xlf"))
        assert out_files, f"no .xlf produced in {out} (found: {list(out.iterdir())})"
        translated = out_files[0]
        content = translated.read_text(encoding="utf-8")
        # Valid XLIFF, with targets filled.
        assert "<xliff" in content
        assert "<target" in content
        # Real translated text > 0 — the OPP XLIFF has empty <target>s;
        # OL fills them.
        # Find at least one <target> with content.
        import re
        targets = re.findall(r"<target[^>]*>([^<]*)</target>", content)
        non_empty = [t.strip() for t in targets if t.strip()]
        assert non_empty, (
            f"no <target> with content filled — XLIFF:\n{content[:1000]}"
        )

    def test_translate_xliff_preserves_source(self, opp_intermediates, tmp_path):
        """The original XLIFF <source> text should survive translation."""
        out = tmp_path / "xlf_preserve"
        proc = run_ol(
            "translate-xliff", str(opp_intermediates["xlf"]),
            "-o", str(out),
            "-s", "en", "-t", "zh",
        )
        assert proc.returncode == 0
        original = opp_intermediates["xlf"].read_text(encoding="utf-8")
        translated = list(out.glob("*.xlf"))[0].read_text(encoding="utf-8")
        # Compare source-text fragments (rough sanity)
        import re
        orig_sources = re.findall(r"<source>([^<]*)</source>", original)
        trans_sources = re.findall(r"<source>([^<]*)</source>", translated)
        assert orig_sources, "no <source> in original XLIFF"
        assert orig_sources == trans_sources, (
            "OL must not modify <source> elements"
        )


class TestExtractWarnings:
    """`ol extract-warnings <file>` — pure file scan, no LLM."""

    def test_extract_warnings_no_warnings(self, opp_intermediates, tmp_path):
        out_file = tmp_path / "warnings.md"
        proc = run_ol("extract-warnings", str(opp_intermediates["md"]),
                      "--output", str(out_file))
        assert proc.returncode == 0, f"stderr: {proc.stderr[:500]}"
        # Either "0 warnings" in stdout or the file says so.
        body = out_file.read_text(encoding="utf-8")
        assert "0 warnings" in body or "No warnings" in body, (
            f"expected 'no warnings' marker in:\n{body}"
        )


class TestJSONOutput:
    """`--json` flag for machine-readable agent integration."""

    def test_translate_md_json(self, opp_intermediates, tmp_path):
        out = tmp_path / "md_json"
        proc = run_ol(
            "translate-md", str(opp_intermediates["md"]),
            "-o", str(out),
            "-s", "en", "-t", "zh",
            "--json",
        )
        assert proc.returncode == 0, f"stderr: {proc.stderr[-1000:]}"
        import json as _json
        # Find a JSON line in stdout.
        for line in proc.stdout.splitlines():
            line = line.strip()
            if line.startswith("{"):
                obj = _json.loads(line)
                assert obj.get("success") is True, f"json: {obj}"
                assert obj.get("output_file"), f"missing output_file: {obj}"
                return
        pytest.fail(f"no JSON object found in stdout:\n{proc.stdout[:1000]}")
